FROM openjdk:17-jdk-slim
RUN apt-get update && apt-get install -y curl
WORKDIR /app
COPY ./target/employee_service-0.0.1-SNAPSHOT.jar /app/employee_service.jar
CMD ["java", "-jar", "employee_service.jar"]