services:
  eureka-server:
    build:
      context: ./eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    healthcheck:
       test: [ "CMD-SHELL", "curl --fail http://localhost:8761/ || exit 1" ]
       interval: 10s
       timeout: 10s
       retries: 5

  employee-service:
    build:
      context: ./employee_service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8081/swagger-ui/index.html || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 5

  company-service:
    build:
      context: ./company_service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8082/swagger-ui/index.html || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 5

  gateway-service:
    build:
      context: ./gateway_service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      company-service:
        condition: service_healthy
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge