FROM openjdk:17-jdk-slim
RUN apt-get update && apt-get install -y curl
WORKDIR /app
COPY ./target/company_service-0.0.1-SNAPSHOT.jar /app/company_service.jar
CMD ["java", "-jar", "company_service.jar"]