FROM openjdk:17-jdk-slim
RUN apt-get update && apt-get install -y curl
WORKDIR /app
COPY ./target/gateway_service-0.0.1-SNAPSHOT.jar /app/gateway_service.jar
CMD ["java", "-jar", "gateway_service.jar"]